<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Version>0.0.2</Version>
    <PackageProjectUrl>https://github.com/Akurosia/AkusEnemySkillTracking</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <IsPackable>false</IsPackable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <Target Name="CopyPluginManifestToOutput" AfterTargets="Build">
    <Copy SourceFiles="$(MSBuildProjectDirectory)\AkusEnemySkillTracking.json"
          DestinationFiles="$(TargetDir)AkusEnemySkillTracking.json"
          SkipUnchangedFiles="true" />
  </Target>
</Project>
